# Generated by Django 2.2.9 on 2020-02-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
