# Generated by Django 2.2.9 on 2020-02-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotogram', '0002_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=11, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
