# Generated by Django 2.2.9 on 2020-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotogram', '0004_auto_20200217_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='like_count',
            field=models.IntegerField(null='true'),
        ),
    ]
